inherit_from: configs/TUM_RGBD/tum_rgbd.yaml
start_idx: 50
stride: 5
early_stop: 2400
rot_thre: 50
trans_thre: 0.5
data:
  input_path: /home/lee/A-LOAM-Container/data/TUM_RGBD/rgbd_dataset_freiburg3_long_office_household/
  output_path: output/TUM_RGBD/rgbd_dataset_freiburg3_long_office_household_final_Noloop_record/
  scene_name: rgbd_dataset_freiburg3_long_office_household
cam: 
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 0
  depth_scale: 5000.0
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]