inherit_from: configs/TUM_RGBD/tum_rgbd.yaml
data:
  input_path: /home/lee/A-LOAM-Container/data/TUM_RGBD/rgbd_dataset_freiburg2_xyz
  output_path: output/TUM_RGBD/rgbd_dataset_freiburg2_xyz_final_1/
  scene_name: rgbd_dataset_freiburg2_xyz
start_idx: 0
stride: 1
early_stop: -1
rot_thre: 30
trans_thre: 0.3
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 520.9
  fy: 521.0
  cx: 325.1
  cy: 249.7
  crop_edge: 50
  depth_scale: 5000.0
  distortion: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172]