inherit_from: configs/TUM_RGBD/tum_rgbd.yaml
data:
  input_path: /home/wujie/ws_0122/data/TUM-RGBD/rgbd_dataset_freiburg1_desk
  output_path: output/TUM_RGBD/rgbd_dataset_freiburg1_desk_mini_ba
  scene_name: rgbd_dataset_freiburg1_desk
start_idx: 50
stride: 2
early_stop: 200
rot_thre: 50
trans_thre: 0.5
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 30
  depth_scale: 5000.0

