inherit_from: configs/TUM_RGBD/tum_rgbd.yaml
data:
  input_path: /home/lee/A-LOAM-Container/data/TUM_RGBD/rgbd_dataset_freiburg1_desk
  output_path: output/TUM_RGBD/rgbd_dataset_freiburg1_desk_ablation_11/
  scene_name: rgbd_dataset_freiburg1_desk
start_idx: 0
stride: 1
early_stop: -1
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 50
