project_name: "LoopSplat_SLAM_utmmrgbd"
dataset_name: "zed720"
checkpoint_path: null
use_wandb: False
frame_limit: -1 # for debugging, set to -1 to disable
desired_height: 720
desired_width: 1280
seed: 0
mapping:
  new_submap_every: 80
  map_every: 1
  iterations: 160
  new_submap_iterations: 150
  new_submap_points_num: -1 
  new_submap_gradient_points_num: 60000 
  new_frame_sample_size: -1
  new_points_radius: 0.0001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.5
  submap_using_motion_heuristic: True
  use_normal_reg: true
  use_dist_reg: true
tracking:
  use_pose_utils: true 
  pose_utils:  
    fundmat_samples: 1000  
    max_error: 1.0         
    top_k: 1500
    num_pts_miniba_incr: 1500  
    min_num_inliers: 30  
    pnpransac_samples: 1000  
    iters_miniba_incr: 200  
  use_imu: false
  gt_camera: False
  w_color_loss: 0.6
  iterations: 100
  cam_rot_lr: 0.001
  cam_trans_lr: 0.001
  odometry_type: "const_speed"  # gt, const_speed, odometer
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  odometer_method: "hybrid" # hybrid or point_to_plane
  filter_alpha: False
  filter_outlier_depth: False
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: True
  enable_exposure: False
cam:
  crop_edge: 0
  depth_scale: 1000.0
lc: 
  min_similarity: 0.5
  pgo_edge_prune_thres: 0.25
  voxel_size: 0.02
  pgo_max_iterations: 500
  registration:
    method: "gs_reg"
    base_lr: 5.e-3
    min_overlap_ratio: 0.2
    use_render: False
  min_interval: 3
  final: False