inherit_from: configs/Replica/replica.yaml
start_idx: 50
stride: 2
early_stop: 2400
data:
  scene_name: office0
  input_path: data/Replica-SLAM/Replica/office0/
  output_path: output/Replica/office0/
