inherit_from: configs/Replica/replica.yaml
start_idx: 0
stride: 2
early_stop: 300
data:
  scene_name: office2
  input_path: /home/lee/A-LOAM-Container/data/Replica/office2/
  output_path: output/Replica/office2/
