inherit_from: configs/Replica/replica.yaml
start_idx: 0
stride: 1
early_stop: -1
data:
  scene_name: office4
  input_path: /home/lee/A-LOAM-Container/data/Replica/office4/
  output_path: output/Replica/office4/
