inherit_from: configs/Replica/replica.yaml
start_idx: 0
stride: 1
early_stop: -1
data:
  scene_name: room0
  input_path: /home/lee/A-LOAM-Container/data/Replica/room0/
  output_path: output/Replica/room0/
